version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: portfolio-apache
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    restart: always
    ports:
      - "51111:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-v1.rule=Host(`portfolio-v2.timeuh.fr`)"
      - "traefik.http.routers.portfolio-v1.entrypoints=websecure"
      - "traefik.http.routers.portfolio-v1.tls.certresolver=myresolver"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
  default:
    driver: bridge