version: '3.8'
name: 'portfolio'

services:
  vite:
    image: node:20-alpine
    container_name: vite
    volumes:
      - ./:/app
    ports:
      - '0.0.0.0:51110:5173'
    working_dir: /app
    command: npm run dev
    restart: always
